version: "3"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus:/etc/prometheus:ro"
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: always
