global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: "host"
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:9000
